travis:
  secure:
    BINSTAR_TOKEN: r2TwMTg2NJNFvFx4iKS+kEDi2VgkUCO1yq+v4Lpv/a+SL3VKuBUJiq1YS1diLzDv8z6XfC8GVqJWzP84ccZy6+6BAcyLE+i2BLmiH1T9AAQdaRqj1mPtUI93juZSyG08xQK34G/HXEb/1+AXqPhrKGQ+j6xA9kR/cJR5D2U6dRvJ7oK5kjHWKiJWj7GSjm5MCp86KbIHijwAA5yK1SBtx2dXYhfm3E12lWTZIAMJ+KExsABw7lSzgr1jzS1LUrXfYEQKUhfPpAax8DFHwLKgFH8rd6eTdgk7QJmg8yQlGS331f0xsYXDRzMsSDtmpw4wobf6ngjtvP9NGW5bb6wiYWbQDI3okrWIL0GL3RscQ1zRp78vLKxyH+CWK9FI+BX3QWX/2W3ejGY6IAM+NnxQt50mCjrtWnCfxWNqbmwRgkLWUzXg23HWov5efCEKG2ZqabIKSU8T3CIAccuAhe6lr6dnhIh3sFWJdMKjNnVJs1U5dXaUbN4seE1v2QHUmWsY+0OwE5c2VqyITpUImkeGooCRzxorABEpfcdGg+3LHMmzqpQh5RBiyInwvO1OoTVGemL8Qz6xnE/wseVU9kQobOfGAhRHsMPzyspS5TnPqZTNgndiZM1PeMNZV3PGuWTWRB/QjLVmK48XDxxJeucWWhUa+jc7KlqYd4gpGJDs3Nc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
