appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sV8VG3Rg/rjh79/l2R7KCdj/LxXJbcp2QUkAhRJBRDwWSETYOhKsvvTkOqWSuESxdrTtGV/HtWokFr37wvsXQjmeHGeu2N6pluwUTCulGd45MvbUWPwgxQoVipkB1oMpIezZm7oqIpAQ5x+rJBk3j4iV89T4Q+YImR7cWAV9zbXwpIOjjT8kRBv1pSQDfBbgVCxSh31wsZy9mwPZyf+p35wwuq0mBO4Unm4Se0KePEJy36bnmHvWBiR4VJKL8HJuj+Zi3pYAuNvfvnw4jvOwHgwBMB0tZZ8GXd247nZ/5guMtxWwF/TJZEWNTeH79iaNk199VItPhaxaPUdhPf4ckhOC0QjHN0fxG7jxos4vlCRqGyUEZ2U1zQRYQv1ik3oOjlz7pdXlUA6gS5PjfhSDHrNlLUaHjixwvnzwuGd4+WBtCwkcb6FDA91VK7gCfOVnu4TqnRGoUMIYGluhjmsS0rt9mwCHCKlQlTDy8MEUx3REv0uUNmhW/jEjOaZTcyXJMTVzh+E7cyFxhIDTAmogf/jht6U0ZTHlNYrJz8TNWzDCsF41wC3TqjMbkwZPEQI7Buj30n85tqfMqv13LXNOWuyVniQFnC0zKUmF4+7Q1mxqrK+QLg/5FlM1CdjnosF5M++yjDBi+W3sucUXUYbbti4nQnmq7M3E2hy4/anlxwI=}
